add deps and a retry

diff --git a/root/etc/s6-overlay/s6-rc.d/svc-mod-nextcloud-notify-push-set-url/run b/root/etc/s6-overlay/s6-rc.d/svc-mod-nextcloud-notify-push-set-url/run
--- a/root/etc/s6-overlay/s6-rc.d/svc-mod-nextcloud-notify-push-set-url/run
+++ b/root/etc/s6-overlay/s6-rc.d/svc-mod-nextcloud-notify-push-set-url/run
@@ -2,7 +2,14 @@
 # shellcheck shell=bash
 
 NOTIFY_PUSH_URL=$(echo "$(occ config:system:get overwrite.cli.url)/push")
+RETRY=0
 echo "**** Setting notify_push server URL to ${NOTIFY_PUSH_URL} ****"
-if ! occ notify_push:setup "${NOTIFY_PUSH_URL}"; then
-    echo "**** There was an error setting the notify_push server URL. Please double check your reverse proxy settings as well as the overwrite.cli.url entry in Nextcloud's config.php ****"
-fi
+while ! occ notify_push:setup "${NOTIFY_PUSH_URL}"; do
+    RETRY=$((${RETRY} + 1))
+    if [[ "${RETRY}" -lt 6 ]]; then
+        sleep 3
+    else
+        echo "**** There was an error setting the notify_push server URL. Please double check your reverse proxy settings as well as the overwrite.cli.url entry in Nextcloud's config.php ****"
+        break
+    fi
+done
