Deprecate  mod

diff --git a/root/etc/s6-overlay/s6-rc.d/init-mod-swag-f2bdiscord-add-package/run b/root/etc/s6-overlay/s6-rc.d/init-mod-swag-f2bdiscord-add-package/run
--- a/root/etc/s6-overlay/s6-rc.d/init-mod-swag-f2bdiscord-add-package/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-mod-swag-f2bdiscord-add-package/run
@@ -1,13 +1,20 @@
 #!/usr/bin/with-contenv bash
+echo  "_ _ _ "
+echo  "| | | |"
+echo  "| | | | The f2b to discord mod is deprecated"
+echo  "|_|_|_|"
+echo  "(_|_|_)"
+        
 
-if ! pip list 2>&1 | grep -q "geoip2"; then
+if ! pip list 2>&1 | grep -q "requests"; then
   echo '------------------------------------------------------------------------'
-  echo '| Adding required modules for swag-f2bdiscord to package install list'
+  echo '| Adding required modules for swag-f2bdiscord deprecation message'
   echo '------------------------------------------------------------------------'
-  echo "\
-    requests \
-    argparse \
-    geoip2==3.0.0" >> /mod-pip-packages-to-install.list
+  echo "requests" >> /mod-pip-packages-to-install.list
+fi
+
+if [ ! -f /config/fail2ban/Fail2Ban.py.orig ] && [ -f /config/fail2ban/Fail2Ban.py ]; then
+  mv /config/fail2ban/Fail2Ban.py /config/fail2ban/Fail2Ban.py.orig
 fi
 
 if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
@@ -15,6 +22,3 @@ if [ ! -f /config/fail2ban/Fail2Ban.py ]; then
   chmod +x /config/fail2ban/Fail2Ban.py
 fi
 
-if [ ! -f /config/fail2ban/action.d/discordEmbed.conf ]; then
-  cp /AwesomeFolder/discordEmbed.conf /config/fail2ban/action.d
-fi
