Remove f2b logrotate if service is disabled. Sanity check tarball.

diff --git a/root/etc/cont-init.d/98-crowdsec b/root/etc/cont-init.d/98-crowdsec
--- a/root/etc/cont-init.d/98-crowdsec
+++ b/root/etc/cont-init.d/98-crowdsec
@@ -32,6 +32,11 @@ curl -so \
 
 mkdir -p /tmp/crowdsec
 
+if ! tar -tzf /crowdsec.tar.gz >/dev/null 2>&1; then
+    echo "**** Invalid tarball, could not download crowdsec bouncer ****"
+    exit 1
+fi
+
 tar xf \
     /tmp/crowdsec.tar.gz -C \
     /tmp/crowdsec --strip-components=1
@@ -93,6 +98,7 @@ rm -rf \
 if [[ $CROWDSEC_F2B_DISABLE == "true" ]]; then
     echo "**** Disabling fail2ban Service ****"
     touch /etc/services.d/fail2ban/down
+    rm -rf /etc/logrotate.d/fail2ban
 fi
 
 echo "**** Successfully configured CrowdSec nginx Bouncer ${CROWDSEC_VERSION} ****"
diff --git a/root/etc/s6-overlay/s6-rc.d/init-mod-swag-crowdsec/run b/root/etc/s6-overlay/s6-rc.d/init-mod-swag-crowdsec/run
--- a/root/etc/s6-overlay/s6-rc.d/init-mod-swag-crowdsec/run
+++ b/root/etc/s6-overlay/s6-rc.d/init-mod-swag-crowdsec/run
@@ -32,6 +32,11 @@ curl -so \
 
 mkdir -p /tmp/crowdsec
 
+if ! tar -tzf /crowdsec.tar.gz >/dev/null 2>&1; then
+    echo "**** Invalid tarball, could not download crowdsec bouncer ****"
+    exit 1
+fi
+
 tar xf \
     /tmp/crowdsec.tar.gz -C \
     /tmp/crowdsec --strip-components=1
